# Generated by Django 4.0.6 on 2022-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
