# Generated by Django 4.0.6 on 2022-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date1',
            field=models.DateField(null=True),
        ),
    ]
